<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>

<body>

  <script>

    // async, await (ES8문법)
    // async, await은 각각 Promise와 then을 매우 쉽게 만들어주는 문법이다.

    // ⭐ async 키워드를 쓰면 Promise 오브젝트가 저절로 생성된다.
    // 말 그대로, new Promise() 어쩌구를 할 필요가 없다.
    // 그러나 async키워드는 function 선언 앞에만 붙일 수 있다.
    async function 연산() {
      1 + 1
    } // 이 함수 자체가 Promise가 되어버린다.

    // 그래서 이 함수를 실행할 때 뒤에 then 붙일 수 있음
    연산().then(function () {
      console.log('연산 성공!');
    });
    // (함수를 실행하면 그 자리에 Promise 인스턴스 (new Promise() 로 만든 오브젝트)가 남는다.)



    // ⭐ 함수안에서 연산한 결과를 then 안에서 사용하고 싶다면
    // return 오른쪽에 결과를 적고, then함수에서 파라미터로 받아오면 됨
    async function 연산2() {
      return 1 + 1; // return
    }

    연산2().then(function (결과) {  // 파라미터로 결과값 받아오기
      console.log(결과);
    })



    // ⭐ then() 함수가 귀찮다면 await 키워드를 쓸 수 있다.
    // async 키워드를 쓴 함수 안에서는 await을 사용할 수 있다.
    // await은 그냥 프로미스.then() 대체품이라고 생각하면 된다. (근데 then보다 문법이 훨씬 간단하다는 장점이 있음)


    // 어떤 함수안에서 어려운 연산을 실행한 뒤에 성공/실패를 판정해주는 Promise를 만들고 싶으면?
    async function 어려운연산() {
      var 사실쉬운연산 = new Promise(function (성공, 실패) {
        var 결과 = 1 + 1;
        성공();
        // 성공(결과) // 연산 결과를 출력하거나 그러고 싶다면 성공 함수에 파라미터를 담아주면 됨.
      });
      // 사실쉬운연산.then();
      var 결과 = await 사실쉬운연산;  // 사실쉬운연산 Promise를 기다린 다음에 완료되면 결과를 변수에 담는다.
      console.log(결과);
    };

    어려운연산();

    // (주의) 비동기식처리되는 코드를 담는다면 await 기다리는 동안 브라우저가 잠깐 멈출 수 있다.



    // ⭐ await은 실패하면 에러가 나고 코드가 멈춘다.
    // 아래는 Promise가 실패하는 코드
    async function 더하기() {
      var 어려운연산 = new Promise(function (성공, 실패) {
        실패();
      });

      var 연산결과 = await 어려운연산;
      console.log(연산결과);

    }
    더하기();
    // 어려운연산이라는 Promise가 실패할 경우 await 어려운연산이라는 코드는 에러가 나고 코드실행을 멈춘다. 그래서 하단에 있는 코드들은 더 이상 실행되지 않는다.



    // ⭐ 그래서 Promise가 실패할 경우 코드 실행을 멈추고 싶지 않으면 try catch 구문을 이용한다.
    async function 더하기2() {
      var 어려운연산2 = new Promise(function (성공, 실패) {
        실패();
      });

      try { 
        var 연산결과 = await 어려운연산2;
        console.log(연산결과);
      }
      catch { // try{} 안의 코드가 에러가 나고 멈출 경우 catch{} 내부의 코드를 실행해줌
        // 어려운연산2 Promise가 실패할 경우 실행할 코드
      }

    }
    더하기2();
    // 어려운연산2라는 Promise가 실패()가 안날거라고 확신이 있으면 try/catch를 꼭 쓸필요는 없다. (then 사용하면됨)
  </script>

</body>

</html>